const errorCodes = {
  SVR: 'same value requested',
  SVA: 'same address requested',
  ZVL: 'zero-value',
  NZA: 'zero-address',
  UTR: 'underflow range',
  NCR: 'non-borrower',
  NPM: 'not a prime member',
  DET: 'deposit window exceeds tenor',
  TTS: 'tenor is too short for monthly loan',
  DWC: 'deposit window closed',
  AAI: 'invalid asset address',
  OAC: 'pool closed',
  OPP: 'only private pool',
  MAC: 'member already created',
  AAD: 'action already done',
  OSE: 'pool size exceeded',
  OHD: 'pool have debts',
  LLZ: 'lender list is zero',
  LZL: 'lender principal is zero',
  IMB: 'invalid member (blacklisted) or not created',
  EAL: 'exceed max array limit',
  EMD: 'exceed maturity date',
  ARM: 'active roll request missing',
  RAR: 'roll already requested',
  RCR: "roll can't be requested",
  RTR: 'roll invalid time range',
  RSI: 'risk score invalid',
  TIF: 'token insert failed',
  BLS: "borrower can't be a member of the pool",
  EDR: 'early default request',
  NBL: 'not bullet loan',
  NML: 'not monthly loan',
  RTE: 'repayment too early',
  PRI: 'penaltyRate invalid'
}

export default errorCodes
